### PR TITLE
Release v2.1.2

### LINKED ISSUE #171: The editor crashes when exiting playmode while it is creating the LLM service
### Describe the bug

This happens if asynchronous startup is true. When you exit playmode after the "Server command" log but before the "LLM service created" log, then the editor just closes.

### Steps to reproduce

_No response_

### LLMUnity version

2.0.0

### Operating System

Windows

### LINKED ISSUE #212: Hot-swap LoRA with updated llama.cpp
### Feature

Since the PRs linked below in llama.cpp, it is possible to how-swap lora adapters. This allows to personalise NPCs and other GenAi game features by fine-tuning adapters that then can be quickly swapped on the same base model in memory.

Since llama.cpp has is being updated in #209. It would be nice to check how easily one can integrate this feature. 

### Todo list

- [x] `bin` files for adapters are now deprecated in favour of new `gguf` files, which should be ameneded in the documentation, if appearing.
- [ ] Add in documentation link to how to convert adapters to `gguf`.
- [x] Test on using the new gguf formats should be run (I suspect the new adapter will automatically be used in hot-swapping mode)
- [x] Test using multiple adapters and hot swapping them, add code if needed, and add an example in the examples folder.

### Related links

Hot lora PRs in llama.cpp:
- Cli: https://github.com/ggerganov/llama.cpp/pull/8332
- Server: https://github.com/ggerganov/llama.cpp/pull/8857

Discord threads:
- [Discussion on lora](https://discord.com/channels/1194779009284841552/1265657308244086815/1266469723240140832)

### PR DESCRIPTION
**Pull request by amakropoulos**
- closes #212 
- closes #171

### CODE REVIEW

**Comment by ltoniazzi** [comment]
I was trying to check the adapters work using the test gguf files from llama.cpp (generated by running [test-lora-conversion-inference.sh](https://github.com/ggerganov/llama.cpp/blob/master/tests/test-lora-conversion-inference.sh), or you can find the gguf files directly [here](https://huggingface.co/ltoniazzi/reduce-llms-for-testing/tree/main/Phi3ForCausalLM/hidden_size%3D64)).

These models are overfitted to return the same sentence for the same initial word, but I am struggling to make them work in branch `release/v2.1.2`. I think it's because the prompt is in formatted as a  chat, so a user saying `Hello` sends
```bash
"<|user|>\nHello<|end|>\n<|assistant|>\n"
```
Instead of (as in llama.cpp tests)
```bash
"<bos>Hello"
```

Would it be helpful if I train similarly small overfitted models to test different adapters respond correctly in a chat?
Then they can be used to test the hot-swapping as well.

**Comment by amakropoulos** [comment]
Yes, you can use `Complete("<bos>Hello")` instead that doesn't use template.

**Comment by ElevenGameStudios** [comment]
I tired this branch in Unity via github URL and it loads Llama3.1 and Gemma models fine, but only in CPU mode. Using cuda via numGPULayers variable crashes Unity/Editor for me right now, whereas the asset store version does not. Using latest Unity 6 preview 15f1, Win10.
Just wanted to let you know. Thanks for this llama.cpp Unity port, overall it works quite nice.

**Comment by amakropoulos** [comment]
@ElevenGameStudios thanks for sending.
What GPU do you have?
Could you send me the Editor.log file when you run the scene and crashes?
It would be very helpful if you could join the [Discord channel](https://discord.gg/RwXKQb6zdv) to send you some other build to try.

**Comment by amakropoulos** [comment]
> > Yes, you can use Complete("Hello") instead that doesn't use template.
> 
> Nice, I tested the adapter is working correctly!
> 
> I am planning to test out what happens when multiple adapters are loaded, because in that case one probably should use the[ param](https://github.com/undreamai/LLMUnity/issues/212) `--lora-init-without-apply` when spinning up the server for the same base model, to be able to swap between adapters.

You can use multiple adapters at the same time, they are all initialised with scale 1.
Then you can use the `SetLoraScale` function to adjust the scale how you want.
I'm adapting the code to make it possible to set weights before the LLM starts

> Not sure what happens now if two LLM use same base but different adapters. Do two different servers spin-up? Have you already looked into this?

Yes each different LLM object starts a new LLM server.

**Comment by ElevenGameStudios** [comment]
> @ElevenGameStudios thanks for sending. What GPU do you have? Could you send me the Editor.log file when you run the scene and crashes? 
I have a Nvidia 3070 RTX 8GB. It seems to crash before the point the "Using architecture: ..." log is sent. The 2.1.1. version runs cuda just fine.
I joined the discord, will send the Editor log file there.

**Comment by amakropoulos** [comment]
closing in favor of #220 because it is not a minor release anymore :)

**Pull request closed without merging**
